package cl.malliq.app.data.repository

import cl.malliq.app.data.local.dao.AlertaDao
import cl.malliq.app.data.local.dao.LocalDao
import cl.malliq.app.data.local.dao.LocatarioDao
import cl.malliq.app.data.local.entity.AlertaEntity
import cl.malliq.app.data.local.entity.LocalEntity
import cl.malliq.app.data.local.entity.LocatarioEntity
import cl.malliq.app.domain.repository.AlertaRepository
import cl.malliq.app.domain.repository.LocalRepository
import cl.malliq.app.domain.repository.LocatarioRepository
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class LocalRepositoryImpl @Inject constructor(
    private val dao: LocalDao
) : LocalRepository {
    override fun observarPorActivo(activoId: String): Flow<List<LocalEntity>> = dao.observarPorActivo(activoId)
    override suspend fun obtenerPorIds(ids: List<String>): List<LocalEntity> = dao.obtenerPorIds(ids)
    override suspend fun upsert(local: LocalEntity) = dao.upsert(local)
}

@Singleton
class LocatarioRepositoryImpl @Inject constructor(
    private val dao: LocatarioDao
) : LocatarioRepository {
    override fun observarPorActivo(activoId: String): Flow<List<LocatarioEntity>> = dao.observarPorActivo(activoId)
    override fun observarPorId(id: String): Flow<LocatarioEntity?> = dao.observarPorId(id)
    override suspend fun upsert(locatario: LocatarioEntity) = dao.upsert(locatario)
}

@Singleton
class AlertaRepositoryImpl @Inject constructor(
    private val dao: AlertaDao
) : AlertaRepository {
    override fun observarPorActivo(activoId: String): Flow<List<AlertaEntity>> = dao.observarPorActivo(activoId)
    override fun contarNoLeidas(activoId: String): Flow<Int> = dao.contarNoLeidas(activoId)
    override suspend fun marcarLeida(id: String) = dao.marcarLeida(id)
    override suspend fun regenerar(activoId: String) { /* generated by use case */ }
}
